### ISSUE TITLE
Tooling doc refers to drush, db-import comment refers to composer

### ISSUE THREAD

**Issue by pkiff** [lando/lamp#61]
The  tooling doc refers to drush (from the drupal recipe). Also, the comment for `lando db-import` in the usage examples refers to composer instead of sql. 

Replacing drush with mysql should fix the first one. Rewriting the comment should fix the second.

**Comment by pkiff** [comment]
Tried to create a simple Pull Request #62 with a suggested fix. Apologies if this just creates more work to fix the issue. I don't know how to do a proper PR!

**Comment by reynoldsalec** [comment]
Thanks @pkiff, merged your PR, should deploy to the docs shortly!
